version: "3.8"

services:
  app:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - API_PORT=8080
      - RUN_MODE=local
      - DATABASE_URL=host=db port=5432 user=admin password=admin dbname=postgres sslmode=disable
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - 8080:8080
    networks:
      - db-net

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - db-net

networks:
  db-net:
