service: rds-setup-2

provider:
  name: aws
  region: us-east-1
  stage: dev

resources:
  Resources:
    # RDS Instance Configuration
    MyPostgresRDS:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: my-postgres-db
        DBInstanceClass: db.t3.micro
        Engine: postgres
        EngineVersion: 16.3
        MasterUsername: postgres
        MasterUserPassword: postgres 
        DBName: postgres
        AllocatedStorage: 20
        PubliclyAccessible: true
        MultiAZ: false
        BackupRetentionPeriod: 7

    # Security Group for RDS Instance
    MyRDSSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: "Allow access to Postgres RDS instance"
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '5432'
            ToPort: '5432'
            CidrIp: 0.0.0.0/0 # This allows access from anywhere; restrict in production

  Outputs:
    DatabaseURL:
      Value: !Sub "postgresql://postgres:postgres@${MyPostgresRDS.Endpoint.Address}:5432/postgres"
      Export:
        Name: DatabaseURL2-${self:provider.stage}