DROP TABLE IF EXISTS MovimentoFinanceiro;
DROP TABLE IF EXISTS Avaliacao;
DROP TABLE IF EXISTS PreferenciasDeNotificacao;
DROP TABLE IF EXISTS Transacao;
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS Evento;
DROP TABLE IF EXISTS Usuario;
DROP TABLE IF EXISTS Tenant;