// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Avaliacao                 string
	Evento                    string
	Movimentofinanceiro       string
	Preferenciasdenotificacao string
	Tenant                    string
	Ticket                    string
	Transacao                 string
	User                      string
	Usuario                   string
}{
	Avaliacao:                 "avaliacao",
	Evento:                    "evento",
	Movimentofinanceiro:       "movimentofinanceiro",
	Preferenciasdenotificacao: "preferenciasdenotificacao",
	Tenant:                    "tenant",
	Ticket:                    "ticket",
	Transacao:                 "transacao",
	User:                      "user",
	Usuario:                   "usuario",
}
